### ISSUE TITLE
My IP is blacklisted

### ISSUE THREAD

**Issue by Burkatovskaya** [susam/mathbin#18]
I am very sorry, but my IP is blacklisted. Can I use the project? May be I created too many pages or something like this? I am a teacher and I use your resourse for my online classes. It was really helpful.
Yours, Yulia.

**Comment by susam** [comment]
Hi @Burkatovskaya,

Can you please share the IP address you are trying to visit this project from? Please visit https://ifconfig.me/ and http://ifconfig.co/ to find out your IP address and share it with me.

I am pretty sure the blacklisting is not due to anything you did. It is very likely that there was a lot of spam originating from an IP range in which your IP address falls under. Once you share your IP address with me, I will make sure it is no longer blacklisted.

**Comment by Burkatovskaya** [comment]
Hi,

thank you for your answer, My Ip is 5.136.89.167.

Yours,

Yulia.

________________________________
От: Susam Pal <notifications@github.com>
Отправлено: 25 июня 2020 г. 1:53:53
Кому: susam/mathbin
Копия: Буркатовская Юлия Борисовна; Mention
Тема: Re: [susam/mathbin] My IP is blacklisted (#18)


Hi @Burkatovskaya<https://github.com/Burkatovskaya>,

Can you please share the IP address you are trying to visit this project from? Please visit https://ifconfig.me/ and http://ifconfig.co/ to find out your IP address and share it with me.

I am pretty sure the blacklisting is not due to anything you did. It is very likely that there was a lot of spam originating from an IP range in which your IP address falls under. Once you share your IP address with me, I will make sure it is no longer blacklisted.

**Comment by susam** [comment]
Hi @Burkatovskaya,

Indeed your IP address range was blocked due to spamming issues in the past. I have unblocked it now. Would you please try using http://mathb.in/ now and let me know if the issue is resolved for you?

**Comment by Burkatovskaya** [comment]
Hi,

everything is OK, thanks!


________________________________
От: Susam Pal <notifications@github.com>
Отправлено: 27 июня 2020 г. 22:20:58
Кому: susam/mathbin
Копия: Буркатовская Юлия Борисовна; Mention
Тема: Re: [susam/mathbin] My IP is blacklisted (#18)


Hi @Burkatovskaya<https://github.com/Burkatovskaya>,

Indeed your IP address range was blocked due to spamming issues in the past. I have unblocked it now. Would you please try using http://mathb.in/ now and let me know if the issue is resolved for you?
